AWSTemplateFormatVersion: "2010-09-09"
Description: A crawler lambda function template

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: lambda-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Path: /


  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lambda-crawler
      Description: youtube crawler lambda function app
      Runtime: java8
      Code:
        S3Bucket: 'chaikovskyi-jars-bucket'
        S3Key: 'crawler.jar'

      Handler: org.ua.wozzya.CrawlerHandler::handleEvent
      MemorySize: 500
      Timeout: 900
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn